# Generated by Django 4.1.13 on 2025-03-15 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_attraction_tags_event_tags_alter_attraction_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 20, 6, 53, 754920, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 20, 6, 53, 754540, tzinfo=datetime.timezone.utc)),
        ),
    ]
