# Generated by Django 5.2 on 2025-05-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_attraction_attraction_photo_attraction_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=54.234),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=15.432),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(),
        ),
    ]
