# Generated by Django 4.1.13 on 2025-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_private',
            field=models.CharField(choices=[('PB', 'Public'), ('PV', 'Private')], default='PB', max_length=2),
        ),
    ]
