# Generated by Django 4.2.1 on 2025-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_followed_event_alter_followed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_photo',
            field=models.ImageField(blank=True, upload_to='attractions/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, upload_to='events/%Y/%m/%d/'),
        ),
    ]
