# Generated by Django 4.2.1 on 2025-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='body',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
