# Generated by Django 5.1.1 on 2024-09-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(upload_to='static/img/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
