# Generated by Django 5.1.1 on 2024-09-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_event_event_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_category',
            new_name='categories',
        ),
    ]
